kind: pipeline
name: default

steps:
  - name: lint
    image: node:12-alpine
    commands:
      - npm ci
      - npm run lint
      - npm run prettier
  - name: test
    image: node:12-alpine
    commands:
      - npm run test
      - npm run prepare-coverage
  - name: upload coverage
    image: md5lukas/drone-coveralls:0.1
    settings:
      token:
        from_secret: coveralls_token
      files:
        - ./coverage/lcov.info
  - name: publish
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
      email:
        from_secret: npm_email
    when:
      event:
        - tag

trigger:
  branch:
    exclude:
      - dependabot/**
