kind: pipeline
name: default

steps:
  - name: test
    image: node:alpine
    commands:
      - npm ci
      - npm run lint
      - npm run prettier
      - npm test
  - name: publish
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
      email:
        from_secret: npm_email
    when:
      event:
        - tag

trigger:
  branch:
    exclude:
      - dependabot/**
